language: node_js
node_js:
  - "4.8.1"
cache:
   directories:
      - node_modules
      - $HOME/.meteor/

before_install:
   - npm install -g spacejam
   - export PATH="$HOME/.meteor:$PATH"
   - curl https://install.meteor.com | /bin/sh
before_script:
  - npm install
script:
  - spacejam test-packages ./
