language: node_js
node_js:
  - "4.8.1"
before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - export PATH="$HOME/.meteor:$PATH"
  - "npm install -g spacejam"
  
script: "spacejam test-packages ./"
